StarRocks/starrocks-connector-for-apache-flink

src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java, src/test/java/com/starrocks/connector/flink/StarRocksSinkBaseTest.java, src/test/java/com/starrocks/connector/flink/table/StarRocksSinkManagerTest.java
enhance the error info details when flinkSchema column mismatch with the real table column size,in favor of speed up troubleshooting problems.
=> enhance the error info details when flinkSchema column mismatch with the real table column size

src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java, src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadVisitor.java, src/main/java/com/starrocks/connector/flink/table/StarRocksSinkOptions.java
=> Improve StarRocks sink metrics

src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java, src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadVisitor.java
Try load error log if stream load response contains ErrorURL, this error log is very helpful to users.
=> Try load error log after stream load failed.

src/test/java/com/starrocks/connector/flink/StarRocksSinkBaseTest.java
=> fix ut cases

src/main/java/com/starrocks/connector/flink/table/StarRocksDynamicTableSink.java, src/main/java/com/starrocks/connector/flink/table/StarRocksDynamicTableSinkFactory.java, src/main/java/com/starrocks/connector/flink/table/StarRocksSinkOptions.java
As title says, track the issue 20.
=> [tracking issue20] support sink parallelism

src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadVisitor.java
issue
[https://github.com/StarRocks/flink-connector-starrocks/issues/28](https://github.com/StarRocks/flink-connector-starrocks/issues/28)
=> fix host list iterate.

src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java, src/main/java/com/starrocks/connector/flink/table/source/struct/StarRocksSchema.java, src/test/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRowsTest.java
fix scanning disordered columns  (#65)
=> fix scanning disordered columns

src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java
https://github.com/StarRocks/flink-connector-starrocks/issues/69#issue-1179470641
=> fix exactly once

pom.xml
Add file_encoding property for pom.xml
=> Add file_encoding property for pom.xml

.gitignore, src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicLookupFunction.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java, src/test/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRowsTest.java
* update gitignore & file add license
* Add case
* fix scanning disordered columns
* use concurrentmap and parallelstream
=> fix scanning disordered columns (#78)

pom.xml, src/main/java/com/starrocks/connector/flink/row/sink/StarRocksDelimiterParser.java, src/main/java/com/starrocks/connector/flink/row/sink/StarRocksTableRowTransformer.java, src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunction.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java, src/main/java/com/starrocks/connector/flink/tools/ExecuteSQL.java, src/test/java/com/starrocks/connector/flink/StarRocksSinkBaseTest.java, src/test/java/com/starrocks/connector/flink/manager/sink/StarRocksSinkManagerTest.java, src/test/java/com/starrocks/connector/flink/row/sink/StarRocksGenericRowTransformerTest.java, src/test/java/com/starrocks/connector/flink/row/sink/StarRocksTableRowTransformerTest.java
=> Flink 1.13

pom.xml, src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java, src/main/java/com/starrocks/connector/flink/row/sink/StarRocksDelimiterParser.java, src/main/java/com/starrocks/connector/flink/row/sink/StarRocksTableRowTransformer.java, src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunction.java, src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java, src/main/java/com/starrocks/connector/flink/tools/ExecuteSQL.java, src/test/java/com/starrocks/connector/flink/manager/sink/StarRocksSinkManagerTest.java, src/test/java/com/starrocks/connector/flink/row/sink/StarRocksGenericRowTransformerTest.java, src/test/java/com/starrocks/connector/flink/row/sink/StarRocksTableRowTransformerTest.java, src/test/java/com/starrocks/connector/flink/table/sink/StarRocksStreamLoadVisitorTest.java
=> Flink 1.12

pom.xml, src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java, src/main/java/com/starrocks/connector/flink/row/StarRocksDelimiterParser.java, src/main/java/com/starrocks/connector/flink/row/StarRocksTableRowTransformer.java, src/main/java/com/starrocks/connector/flink/table/StarRocksDynamicSinkFunction.java, src/main/java/com/starrocks/connector/flink/table/StarRocksSinkOptions.java, src/main/java/com/starrocks/connector/flink/tools/ExecuteSQL.java, src/test/java/com/starrocks/connector/flink/manager/StarRocksSinkManagerTest.java, src/test/java/com/starrocks/connector/flink/row/StarRocksGenericRowTransformerTest.java, src/test/java/com/starrocks/connector/flink/row/StarRocksTableRowTransformerTest.java, src/test/java/com/starrocks/connector/flink/table/StarRocksStreamLoadVisitorTest.java
=> Flink 1.11

pom.xml, src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java, src/main/java/com/starrocks/connector/flink/row/sink/StarRocksDelimiterParser.java, src/main/java/com/starrocks/connector/flink/row/sink/StarRocksTableRowTransformer.java, src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunction.java, src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java, src/main/java/com/starrocks/connector/flink/tools/ExecuteSQL.java, src/test/java/com/starrocks/connector/flink/manager/sink/StarRocksSinkManagerTest.java, src/test/java/com/starrocks/connector/flink/row/sink/StarRocksGenericRowTransformerTest.java, src/test/java/com/starrocks/connector/flink/row/sink/StarRocksTableRowTransformerTest.java, src/test/java/com/starrocks/connector/flink/table/sink/StarRocksStreamLoadVisitorTest.java
=> Flink 1.14

README.md, pom.xml, src/main/java/com/starrocks/connector/flink/tools/ExecuteSQL.java, src/test/java/com/starrocks/connector/flink/it/sink/StarRocksDynamicTableSinkITTest.java
=> [Feature] Support Flink 1.15

src/main/java/com/starrocks/connector/flink/row/source/StarRocksToFlinkTranslators.java
=> [BugFix] chinese garbled by non UTF-8

src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicTableSource.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksExpressionExtractor.java, src/test/java/com/starrocks/connector/flink/table/source/StarRocksDynamicTableSourceTest.java
fix #88 
let flink to handle function
=> [BugFix] sql parse error caused by sql function

.gitignore, pom.xml, src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryVisitor.java, src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java, src/main/java/com/starrocks/connector/flink/row/StarRocksCsvSerializer.java, src/main/java/com/starrocks/connector/flink/row/StarRocksGenericRowTransformer.java, src/main/java/com/starrocks/connector/flink/row/StarRocksIRowTransformer.java, src/main/java/com/starrocks/connector/flink/row/StarRocksJsonSerializer.java, src/main/java/com/starrocks/connector/flink/row/StarRocksTableRowTransformer.java, src/main/java/com/starrocks/connector/flink/table/StarRocksDataType.java, src/main/java/com/starrocks/connector/flink/table/StarRocksDynamicSinkFunction.java, src/main/java/com/starrocks/connector/flink/table/StarRocksDynamicTableSinkFactory.java, src/main/java/com/starrocks/connector/flink/tools/ClassUtils.java, src/test/java/com/starrocks/connector/flink/row/StarRocksCsvSerializerTest.java
=> Flink-1.11

src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicLRUFunction.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicLookupFunction.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicTableSource.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksSourceBeReader.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksSourceCommonFunc.java, src/main/java/com/starrocks/connector/flink/table/source/struct/ColumnRichInfo.java, src/main/java/com/starrocks/connector/flink/table/source/struct/StarRocksSchema.java, src/main/java/com/starrocks/connector/flink/tools/DataTypeUtils.java, src/main/java/com/starrocks/connector/flink/tools/DataUtil.java, src/test/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRowsTest.java
=> [BugFix] Read starrocks table data out-of-order

src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java, src/main/java/com/starrocks/connector/flink/row/source/StarRocksToFlinkTranslators.java, src/main/java/com/starrocks/connector/flink/table/source/struct/StarRocksSchema.java
=> [BugFix] Read order

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
=> Fix checkstyle

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/BatchTableRegion.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoadManager.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamTableRegion.java
stream load callback set state = active and then manager test prepare will cancel
this region if the region doesn't have data. when manager flushing data
will trigger future.get() then get this exception
=>  Fix CancellationException

pom.xml
Fix #135 
Reproduced in kinesis flink 1.15.2
org.apache.flink.runtime.rest.handler.RestHandlerException: Could not execute application.
at org.apache.flink.runtime.webmonitor.handlers.JarRunOverrideHandler.lambda$handleRequest$4(JarRunOverrideHandler.java:248)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at …
=> Fix shade jackson

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
=> [Bugfix] callback after check label state succeed

src/test/java/com/starrocks/connector/flink/StarRocksSinkBaseTest.java, src/test/java/com/starrocks/connector/flink/container/OperationManager.java, src/test/java/com/starrocks/connector/flink/container/StarRocksBEContainer.java, src/test/java/com/starrocks/connector/flink/container/StarRocksCluster.java, src/test/java/com/starrocks/connector/flink/container/StarRocksContainer.java, src/test/java/com/starrocks/connector/flink/container/StarRocksContainerException.java, src/test/java/com/starrocks/connector/flink/container/StarRocksFEContainer.java, src/test/java/com/starrocks/connector/flink/container/StarRocksImage.java, src/test/java/com/starrocks/connector/flink/container/StarRocksImageBuilder.java, src/test/java/com/starrocks/connector/flink/it/StarRocksITTest.java, src/test/java/com/starrocks/connector/flink/it/StarRocksITTestBase.java
=> [ITTest] Add ITTest for sink and source.

src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java
Abort transaction if flush failed
=> [Bugfix] Abort transaction if flush failed

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoadResponse.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java
=> [Enhancement] Print error log

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java
Check the http response status code for (transaction) stream load. If it's not `200`, throw exception and log the detail to find the failure reason
=> [Bugfix] Check the http response status code for (transaction) stream load

.github/PULL_REQUEST_TEMPLATE.md
Add pull request template which refers to [StarRocks' template](https://github.com/StarRocks/starrocks/blob/main/.github/PULL_REQUEST_TEMPLATE.md).
=> [Enhancement] Add pull request template

src/main/java/com/starrocks/connector/flink/manager/FlushAndCommitStrategy.java, src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManagerV2.java
=> [Bugfix] the frequency of loading in a transaction should only be controlled by maxCacheBytes

.github/PULL_REQUEST_TEMPLATE.md, src/main/java/com/starrocks/connector/flink/manager/FlushAndCommitStrategy.java, src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManagerV2.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java
=> cherry-pick from main to 1.15

src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicTableSinkFactory.java, src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadProperties.java
=> [Cherry-pick] [Enhancement] Support to configure 100-continue wait timeout #208

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java
Fixes #
transaction stream load can't configure timeout
=> [BugFix] Fix that transaction stream load can't configure timeout

src/main/java/com/starrocks/connector/flink/manager/TransactionTableRegion.java
=> [BugFix] Don't commit if there is no flush in sink

src/main/java/com/starrocks/connector/flink/manager/TransactionTableRegion.java
=> [BugFix] Don't commit if the data is never flushed

pom.xml
=> Bump version to 1.2.7

src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadListener.java, src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/FlushAndCommitStrategy.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StarRocksSinkManagerV2.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadListener.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/TransactionTableRegion.java
Fixes #
Move StarRocksSinkManagerV2 to stream-load-sdk so that other connectors can use it
=> [Refactor] Move StarRocksSinkManagerV2 to stream-load-sdk

src/main/java/com/starrocks/connector/flink/table/sink/SinkFunctionFactory.java, src/test/java/com/starrocks/connector/flink/table/sink/SinkFunctionFactoryTest.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoadUtils.java
=> [Refactor] Move transaction stream load probing to stream load sdk

starrocks-stream-load-sdk/pom.xml, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoadManager.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/EnvUtils.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java
=> [Enhancement] Add git-commit-id-plugin for stream load sdk

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
=> [Enhancement] use info log for DefaultStreamLoader#close

pom.xml, starrocks-stream-load-sdk/pom.xml
Fixes #
if we want to use the framework's jar for sdk, such as httpclient, there is no need to package the dependency repeatedly
with dependency just add `jar-with-dependencies` classifier
```
<dependency>
<groupId>com.starrocks</groupId>
<artifactId>starrocks-stream-load-sdk</artifactId>
<version>1.0-SNAPSHOT</version>
<classifier>jar-with-dependencies</classifier>
</dependency>
```
=> [Enhancement] Generate origin and jar-with-dependencies for sdk

pom.xml, src/test/java/com/starrocks/connector/flink/it/sink/StarRocksDynamicTableSinkITTest.java, src/test/java/com/starrocks/connector/flink/it/sink/StarRocksGenericSinkITTest.java, src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java, src/test/java/com/starrocks/connector/flink/manager/sink/StarRocksSinkManagerTest.java, src/test/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRowsTest.java, src/test/java/com/starrocks/connector/flink/table/sink/SinkFunctionFactoryTest.java, src/test/java/com/starrocks/connector/flink/table/sink/StarRocksStreamLoadVisitorTest.java, src/test/resources/log4j2-test.properties
=> [UT] Add test for upsert and delete for pk

src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java, src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTestBase.java
=> [UT] Add test to delete data for pk partial update

src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunction.java, src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java
=> [Bugfix] Fix NPE if serializer is null

src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java
=> [Bugfix] Don't clear the buffer before flushing when closing for flink-1.13

src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java
=> [UT] Improve StarRocksSinkITTest#testPKPartialUpdateDelete

examples/pom.xml, examples/src/main/java/com/starrocks/connector/flink/examples/datastream/LoadCsvRecords.java, examples/src/main/java/com/starrocks/connector/flink/examples/datastream/LoadCustomJavaRecords.java, examples/src/main/java/com/starrocks/connector/flink/examples/datastream/LoadJsonRecords.java, examples/src/main/resources/log4j2.properties
=> [Examples] Add examples for sink with DataStream api

docs/content/connector-sink.md
=> [Doc] Fix the example of conditional update

src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java, src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicTableSinkFactory.java, src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java, src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/LabelGeneratorFactory.java
=> [Enhancement] Add option  whether to enable exactly-once label generator

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoadConstants.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoadResponse.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/exception/ErrorUtils.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/exception/StreamLoadFailException.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/TransactionTableRegion.java, starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/exception/ErrorUtilsTest.java
=> [Enhancement] Don't retry for some exceptions

src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkTable.java, src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java
Fixes #
fails to write Flink string to StarRocks largeint/json columns. This bug is introduced by #235
=> [Bugfix] Fix that fail to write data to largeint/json columns

src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
=> [Refactor] Rename some exactly-once options

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/TransactionTableRegion.java
=> [Enhancement] Reuse the label for retry to avoid duplicate load

src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DelimiterParser.java, starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/DelimiterParserTest.java
=> [Enhancement] Add delimiter parser in sdk for common use

deploy.sh, pom.xml
=> Bump version to next 1.2.9

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java
Fixes https://github.com/StarRocks/starrocks-connector-for-apache-flink/issues/290
* When using spark operate starrocks, log and thread is error. I don’t think it’s necessary to show in the thread whether spark or flink is used.
=> [Bugfix] Fix thread name and log (#290)

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadTableProperties.java
=> [hotfix] Add enableUpsertDelete back to StreamLoadTableProperties

examples/pom.xml, examples/src/main/java/com/starrocks/connector/flink/examples/datastream/WriteMultipleTables.java
=> [Tool] Add example for writing to multiple tables

src/main/java/com/starrocks/connector/flink/table/sink/SinkFunctionFactory.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/RecordSerializer.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/RowDataSerializer.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/StarRocksSink.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/StarRocksWriter.java
=> [Refactor] Introduce a input record serializer for new sink api

src/main/java/com/starrocks/connector/flink/table/sink/SinkFunctionFactory.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/RowDataSerializationSchema.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/StarRocksRecordSerializationSchema.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/StarRocksSink.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/StarRocksWriter.java
=> [Refactor] Rename RecordSerializer to StarRocksRecordSerializationSchema

src/main/java/com/starrocks/connector/flink/table/sink/SinkFunctionFactory.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/RecordSerializationSchema.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/RowDataSerializationSchema.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/StarRocksSink.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/StarRocksWriter.java
=> [Refactor] Rename StarRocksRecordSerializationSchema to RecordSerializationSchema

src/main/java/com/starrocks/connector/flink/table/sink/v2/DefaultStarRocksSinkContext.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/RecordSerializationSchema.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/RowDataSerializationSchema.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/StarRocksSink.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/StarRocksSinkContext.java, src/main/java/com/starrocks/connector/flink/table/sink/v2/StarRocksWriter.java
=> [BugFix] Fix NPE if RecordSerializationSchema#serialize returns null

src/main/java/com/starrocks/connector/flink/catalog/FlinkCatalog.java, src/main/java/com/starrocks/connector/flink/catalog/JdbcUtils.java, src/main/java/com/starrocks/connector/flink/catalog/StarRocksCatalog.java, src/test/java/com/starrocks/connector/flink/it/StarRocksITTestBase.java, src/test/java/com/starrocks/connector/flink/it/catalog/StarRocksCatalogTest.java
=> [BugFix] Fix StarRocksCatalog#databaseExists sql format error 

src/main/java/com/starrocks/connector/flink/catalog/FlinkCatalog.java, src/main/java/com/starrocks/connector/flink/catalog/StarRocksCatalog.java
=> [Enhancement] Remove common-compress dependency

pom.xml
=> Bump version to 1.2.10

docs/content/Realtime synchronization from MySQL.md, pom.xml, src/main/java/com/starrocks/connector/flink/catalog/StarRocksCatalog.java, src/main/java/com/starrocks/connector/flink/catalog/starrocks/DataModel.java, src/main/java/com/starrocks/connector/flink/catalog/starrocks/StarRocksType.java, src/main/java/com/starrocks/connector/flink/cdc/DatabaseSync.java, src/main/java/com/starrocks/connector/flink/cdc/DateToStringConverter.java, src/main/java/com/starrocks/connector/flink/cdc/SourceSchema.java, src/main/java/com/starrocks/connector/flink/cdc/StarRocksCdcTools.java, src/main/java/com/starrocks/connector/flink/cdc/StarRocksOptions.java, src/main/java/com/starrocks/connector/flink/cdc/json/DebeziumJsonFilter.java, src/main/java/com/starrocks/connector/flink/cdc/json/DebeziumJsonProcess.java, src/main/java/com/starrocks/connector/flink/cdc/json/DebeziumJsonSerializer.java, src/main/java/com/starrocks/connector/flink/cdc/mysql/MysqlDatabaseSync.java, src/main/java/com/starrocks/connector/flink/cdc/mysql/MysqlType.java, src/main/java/com/starrocks/connector/flink/cdc/mysql/ParsingProcessFunction.java, src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java, src/main/java/com/starrocks/connector/flink/tools/IOUtils.java, src/test/java/com/starrocks/connector/flink/cdc/StarRocksCdcToolsTest.java
=> [Feature] Support to synchronize mysql entire databases 

src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java, src/test/java/com/starrocks/connector/flink/it/source/StarRocksSourceITTest.java
=> [BugFix] Remove column name check for arrow

src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicLookupFunction.java, src/test/java/com/starrocks/connector/flink/it/source/StarRocksSourceITTest.java
Fixes #
StarRocksSourceBeReader is not closed after finishing reading data
=> [BugFix] Close StarRocksSourceBeReader in StarRocksDynamicLookupFunction

examples/src/main/java/com/starrocks/connector/flink/examples/datastream/WriteMultipleTables.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadProperties.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/FlushReason.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java, starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/TransactionTableRegion.java
Fixes #
Support to set warehouse when using transaction stream load. This PR also refine some logs
=> [Enhancement] Support to set warehouse when using transaction stream load

starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadProperties.java
判断有误导致自定义properties无法添加进httpPut的header中
=> [BugFix] Fail to add custom stream load table properties

common.sh, pom.xml, src/test/java/com/starrocks/connector/flink/it/sink/kafka/KafkaTableTestUtils.java
=> [Feature] Support Flink 1.19

src/main/java/com/starrocks/connector/flink/row/source/ArrowFieldConverter.java, src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java, src/test/java/com/starrocks/connector/flink/it/source/StarRocksSourceITTest.java
=> [UT] Add tests for reading and write StarRocks DATETIME

pom.xml
=> Bump version to 1.2.11-SNAPSHOT

src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java
=> Removing data row from warn logs to avoid exposing payload in logs

src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicTableSource.java, src/main/java/com/starrocks/connector/flink/table/source/StarRocksSourceOptions.java, src/main/java/com/starrocks/connector/flink/table/source/struct/PushDownHolder.java, src/test/java/com/starrocks/connector/flink/table/source/StarRocksDynamicTableSourceTest.java, src/test/java/com/starrocks/connector/flink/table/source/StarRocksSourceOptionsTest.java, src/test/java/com/starrocks/connector/flink/table/source/struct/PushDownHolderTest.java
=> [BugFix] Deep copy StarRocksDynamicTableSource

pom.xml
=> Bump version to 1.2.12-SNAPSHOT

pom.xml, starrocks-stream-load-sdk/pom.xml
=> [Enhancement] Use central-publishing-maven-plugin for deploy

pom.xml
=> Bump version to 1.2.13-SNAPSHOT
