- pom.xml
- src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java
- src/main/java/com/starrocks/connector/flink/row/sink/StarRocksDelimiterParser.java
- src/main/java/com/starrocks/connector/flink/row/sink/StarRocksTableRowTransformer.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunction.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
- src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java
- src/main/java/com/starrocks/connector/flink/tools/ExecuteSQL.java
- src/test/java/com/starrocks/connector/flink/manager/sink/StarRocksSinkManagerTest.java
- src/test/java/com/starrocks/connector/flink/row/sink/StarRocksGenericRowTransformerTest.java
- src/test/java/com/starrocks/connector/flink/row/sink/StarRocksTableRowTransformerTest.java
- src/test/java/com/starrocks/connector/flink/table/sink/StarRocksStreamLoadVisitorTest.java
Fix problem below and modify some code style
```
org.apache.flink.api.common.InvalidProgramException: [] is not serializable. The object probably contains or references non serializable fields.
```
> Fix object can not be serialized error in sink

- src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadVisitor.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
In production, we find that all writes are on a single node, which would result in a high load on a single node.
So implement balanced writes to StarRocks each node.
> [Improvement] Implement balanced writes to StarRocks each node

- src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkTable.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
Fix #129 
When use flink sql transfer to sr from cdc, and not set sink.properties.columns. the Flink Tableschema columns are not sync to set StreamLoadTableProperties columns in sdk.
> Fix flink sql upsert delete

- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java
Fixes #
`StarRocksDynamicSinkFunctionV2#legacyData` is transient, and should be initialized in `StarRocksDynamicSinkFunctionV2#initializeState()`, otherwise NPE will be thrown when accessing it
> [Bugfix] Initialize StarRocksDynamicSinkFunctionV2#legacyData in initializeState() to avoid NPE

- src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java
- src/main/java/com/starrocks/connector/flink/table/source/StarRocksSourceBeReader.java
Fixes #
1. `StarRocksDynamicSourceFunction` does not close `StarRocksSourceDataReader` if flink job finishes normally, which will not close the connection with BE
2. check the configuration for `keepAliveMin` does not overflow when converting `int` to `short`
> [Bugfix] Always close StarRocksSourceDataReader and check keepAliveMin is valid

- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
The default timeout for transaction stream load is 120 seconds. But it's normal to set Flink checkpoint interval to minutes, so the Flink job will easily fail because of transaction timeout. This PR suggest to increase the default timeout to 600s which is also the StarRocks' [default value](https://github.com/StarRocks/starrocks/blob/main/fe/fe-core/src/main/java/com/starrocks/common/Config.java#L750).
The timeout message likes 
```
com.starrocks.data.load.stream.exception.StreamLoadFailException: {
"TxnId": 33823381,
"Label": "502c2770-cd48-423d-b6b7-9d8f9a59e41a",
"Status": "Fail",
"Message": "timeout by txn manager",
"NumberTotalRows": 1637,
"NumberLoadedRows": 1637,
"NumberFilteredRows": 0,
"NumberUnselectedRows": 0,
"LoadBytes": 4284214,
"LoadTimeMs": 120294,
"BeginTxnTimeMs": 0, …
```
> [Enhancement] Make transaction stream load default timeout to 600s

- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoadManager.java
Fixes #155 
Fail to delete data when using json format to load data to primary key table. The reason is that `StarRocksJsonSerializer` is created before `SinkOptions#supportUpsertDelete()` is decided so that the serializer will not add `__op` column to the json, and StarRocks will treat it as an upsert
> [Bugfix] Fail to delete data when using json format

- src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkTable.java
- src/main/java/com/starrocks/connector/flink/row/sink/StarRocksTableRowTransformer.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java
Fixes #159 
Can't map a Flink `String` column(json string) to StarRocks  `JSON` column. The reason is that `StarRocksDynamicSinkFunctionV2` does not set `StarRocksTableRowTransformer#columns`, and `StarRocksTableRowTransformer#typeConvertion` will not check whether the received data is a json string, and can't map it to StarRocks `JSON`.
> [Bugfix] Can't load data to StarRocks json column

- pom.xml
- starrocks-stream-load-sdk/pom.xml
maven-gpg-plugin needs to install gpg and input password when installing/deploying the package. It is mainly used to do digital signature when releasing a package. But it's not convenient for development purpose, for example, only install the package to local repo, so move the plugin to the scope of `release` profile, and enable it when releasing a package
> [Enhancement] Only use maven-gpg-plugin when releasing package

- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadTableProperties.java
Fixes #171 
When setting default `columns` http header, add backtick`` ` ` `` to column names to support sql keywords
* Mysql cdc -> StarRocks
* starrocks connector 1.2.4, 1.2.5
Mysql table
```
CREATE TABLE `lpf`.`test_kw` (
`id` int(11) NOT NULL,
`partition` int(11) DEFAULT NULL,
`create` int(11) DEFAULT NULL,
PRIMARY KEY (`id`)
);
```
StarRocks table
```
CREATE TABLE `lpf`.`test_kw` (
`id` int(11) NOT NULL COMMENT "",
`partition` int(11) NULL COMMENT "",
`create` int(11) NULL COMMENT ""
) ENGINE=OLAP
PRIMARY KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);
```
Flink SQL
```
CREATE DATABASE IF NOT EXISTS `default_catalog`.`lpf`;
CREATE TABLE IF NOT …
```
> [Bugfix] add backtick to column names to support SQL keywords

- starrocks-stream-load-sdk/pom.xml
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoadManager.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StarRocksVersion.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadProperties.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/DefaultStreamLoadManagerTest.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/StarRocksVersionTest.java
SR <= 2.2 does not support to ingest json format data via http chunk, otherwise the stream load will fail with the error message "all partitions have no load data". This pr will choose the way to send json format data according to starrocks' version. For SR <= 2.2, not use http chunk (`BatchTableRegion`), otherwise use the chunk mode (`StreamTableRegion`).
> [Bugfix] Not use http chunk to send json format data for starrocks<=2.2

- src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java
- src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManagerV2.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/BatchTableRegion.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoadManager.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/LoadMetrics.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/io/StreamLoadStream.java
When using at-least-once + json, V2 is much slower than V1 (commit cbbe1f10f7e05f47952a095ff9ad138549026c5c). This PR will optimize the performance in the following aspects
* opt1: use `BatchTableRegion` rather than `StreamTableRegion`, because `BlockingQueue` in `StreamTableRegion` costs too much. V1 uses a similar batch method
* opt2: make write and stream load concurrently which is same as V1
* opt3: let `StreamLoadStream` uses `HeapByteBuffer.get` (backed by `System.arrayCopy`) to make data copy more efficiently
`V2/V1` denotes the ratio of time to ingest the same amount  of data
| Opt      | V2 / V1 |
| ----------- | ----------- |
| base      | 2.07       |
| opt 1      | 1.66        |
| opt 1+2      |   1.07 |
| opt 1+2+3      | 1.00 |
> [Enhancement] Optimize the performance of sink V2

- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadTableProperties.java
introduced by #173. Don't add backticks when `sink.properties.columns` is configured
> [Bugfix] Don't add backtick if columns is configured

- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoadDataFormat.java
CSV will always add first/end new line delimiter , and it will lead to wrong result if a none new-line delimiter is specified
> [Bugfix] Don't add first/end new line delimiter for csv

- src/main/java/com/starrocks/connector/flink/table/sink/SinkFunctionFactory.java
Remove http prefix when probing transaction load, and `SinkFunctionFactoryTest#testIsStarRocksSupportTransactionLoad` should pass
> [Bugfix] Remove http prefix when probing transaction load

- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoadDataFormat.java
For transaction stream load, need to append the row delimiter to the end of each load, and separate the data in multiple loads. For example, there are 3 columns, column delimiter ",", row delimiter "\n". There are 2 rows (1, 2, 3), (4, 5, 6), and send them in two loads. If not append the end delimiter, the data received by StarRocks will be "1,2,34,5,6", the two rows are not separated by row delimiter, and StarRocks will parse it as one line with 5 columns. After appending the end delimiter, it will be "1,2,3\n4,5,6", which will be parsed correctly
> [Bugfix] Append csv row delimiter to the end in the transaction load

- src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadVisitor.java
- src/test/resources/log4j2-test.properties
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
`DefaultStreamLoader#getAvailableHost()` and `StarRocksStreamLoadVisitor#getAvailableHost()` will go into dead loop if the load url is wrong and can't be connected
> [Bugfix] Fix dead loop of getAvailableHost() when load url is wrong

- src/main/java/com/starrocks/connector/flink/manager/TransactionTableRegion.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java
The case is:
1. Flink job complete checkpoint 1, and commit the transaction with label `label1`
2. StarRocks FE leader restarts for some reasons, such as upgrade, and flink job fails because FE is down
4. After FE is restarted, flink job restores from checkpoint 1, and re-commit the transaction with label `label1`, but FE returns a failed status with error message like `UserException: transaction with op commit label 154968ac-c52b-4ae9-8fdf-1df64f285b96 has no backend` (see [TransactionLoadAction#executeTransaction](https://github.com/StarRocks/starrocks/blob/main/fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java#L119) for details)
5. Commit failure will trigger the flink job failure again, and in a dead loop, but actually the transaction has been committed …
> [Bugfix] Check label state if fail to commit because FE restarts

- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java
Fixes #
According to the [doc](https://docs.starrocks.io/en-us/latest/loading/Stream_Load_transaction_interface#return-result-4), the returned response for a successful rollback of transaction stream load should be 
```
{
"TxnId": 1,
"Label": "a25eca8b-7b48-4c87-9ea7-0cbdd913e77d",
"Status": "OK",
"Message": ""
}
```
The `Status` field is `OK`, but currently `TransactionStreamLoader#rollback` thinks it's `Success`, and will treat a successful  rollback as a failure.
> [Bugfix] The returned result for transaction rollback should be "OK"

- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicTableSinkFactory.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadProperties.java
Fixes #
HTTP request for load need carry the header `Expect` with the value `100-continue` (see [doc](https://docs.starrocks.io/en-us/latest/sql-reference/sql-statements/data-manipulation/STREAM%20LOAD#syntax) for the detail). HTTP client will deal with the request in the following steps
1. send the header to StarRocks' FE
2. wait for the response from FE to redirect to StarRocks' BE
3. send the header and body  to BE
In step 2,  the client will send the body to FE if not receive the response in some time (default 3000 ms), and the logic is only valid when the request is 100-continue.(see [HttpRequestExecutor#doSendRequest](https://github.com/apache/httpcomponents-core/blob/rel/v4.4.6/httpcore/src/main/java/org/apache/http/protocol/HttpRequestExecutor.java#L192) for the detail). This …
> [Enhancement] Support to configure 100-continue wait timeout

- src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadVisitor.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java
Fixes #
currently `StarRocksStreamLoadVisitor#checkLabelState` and `DefaultStreamLoader#getLabelState` will continue retrying if not get the expected label state. This may be caused by the bug of StarRocks, such as https://github.com/StarRocks/starrocks/pull/21127. In this case, connector is better to throw some exception to tell the flink user what happens rather than stuck here, and then can investigate the problem.
> [Enhancement] Exit getLabelState() if retry for more than a certain time

- src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicTableSinkFactory.java
Fixes #
some useful metrics for sink V1. `flushTimeNsWithRetry`, `totalFlushRetry` and `flushRetry` are added in this PR
metric | 描述 | 类型 | 单位
-- | -- | -- | --
totalFlushRows | flush数据总条数 | counter |  
totalFlushBytes | flush数据总bytes | counter | byte
totalFlushSucceededTimes | flush次数 | counter |  
totalFlushTimeNs | flush数据总耗时(包括重试) | counter | nano
totalFlushTimeNsWithoutRetries | flush数据总耗时(不包括重试) | counter | nano
flushTimeNs | 成功flush的耗时(不包括重试) | Histogram | nano
**flushTimeNsWithRetry** | 成功flush的耗时(包括重试) | Histogram | nano
**totalFlushRetry** | 所有成功flush的重试总数 | counter |  
**flushRetry** | 成功flush的重试数 | Histogram |  
</div></div><span data-lark-record-data="{&quot;isCut&quot;:false,&quot;rootId&quot;:&quot;doxcnhGGeFDoRteHjhOoeYHxd0e&quot;,&quot;parentId&quot;:&quot;doxcnuJ3pJDoeKkW …
> [Enhancement] Add retry metrics for sink version V1

- src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java
Fixes #
StarRocksSinkManager#checkFlushException will log current stack trace. It's not useful for troubleshooting, but occupies much of disk space if failover is frequent, so remove this log.
> [Enhancement] Remove useless stack trace log for sink V1

- src/main/java/com/starrocks/connector/flink/table/sink/SinkFunctionFactory.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicTableSinkFactory.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
Fixes #
Transaction stream load is not always perfect for at-least-once. For example, it will open a long-running transaction, and is more easy to reach the limit of the max running transactions. So provide an option to use the normal stream load for at-least-once.
> [Enhancement] Support to configure whether to use transaction stream load for at-least-once

- src/main/java/com/starrocks/connector/flink/manager/StarRocksQueryVisitor.java
- src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkTable.java
- src/main/java/com/starrocks/connector/flink/table/sink/SinkFunctionFactory.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunction.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
- src/test/java/com/starrocks/connector/flink/it/StarRocksITTest.java
- src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkTest.java
Fixes #
Currently if users want to write only partial columns into StarRock, need to specify `sink.properties.columns` to tell the column names of these partial columns, but it's actually not necessary because users already define these columns when creating a flink table, and the connector can get those information from the table schema. 
This PR contains these improvements
* infer whether it's partial write by comparing the schemas between Flink and StarRocks
* if it's partial write, the connector will set `sink.properties.columns` automatically, otherwise this parameter can be omitted
> [Enhancement] Detect partial columns write according to Flink schema

- starrocks-stream-load-sdk/pom.xml
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoadManager.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoadDataFormat.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoadStrategy.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoadUtils.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadProperties.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/StreamLoadResponseTest.java
Fixes #
Spark/Flink both use jackson to serialize/deserialize json, so it's possible to reuse the jackson jar from the frameworks if the sdk also uses jackson rather than fastjson, and the sdk will be smaller and there is no need to shade for json dependency. This pr replaces the fastjson with jackson.
> [Enhancement] Replace fastjson with jackson in stream-load-sdk

- pom.xml
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicTableSinkFactory.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
- starrocks-stream-load-sdk/pom.xml
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/BatchTableRegion.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/Chunk.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamTableRegion.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TableRegion.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadProperties.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/ChunkHttpEntity.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/ChunkInputStream.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/TransactionTableRegion.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/ChunkHttpEntityTest.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/ChunkInputStreamTest.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/ChunkTest.java
Fixes #
Support to retry for normal stream load if it failed. Currently the retry for transaction stream load is not supported.  The advantage of transaction load is to save memory usage. It splits data into batches, and release the memory for each batch after sending it to StarRocks. If support to retry, need to buffer all data in memory before the last batch success, and the memory usage will not be reduced. this will lose the advantage of transaction stream load
> [Enhancement] Support to retry for normal stream load

- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java
> [Enhancement] Support to get exception in stream-load-sdk

- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
- src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java
Fixes #
By default, using json format should enable strip_outer_array and ignore_json_size which can improve the ease of use
> [Enhancement] Enable strip_outer_array and ignore_json_size by default

- src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java
- src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadVisitor.java
- src/main/java/com/starrocks/connector/flink/row/sink/StarRocksCsvSerializer.java
- src/main/java/com/starrocks/connector/flink/row/sink/StarRocksIRowTransformer.java
- src/main/java/com/starrocks/connector/flink/row/sink/StarRocksISerializer.java
- src/main/java/com/starrocks/connector/flink/row/sink/StarRocksJsonSerializer.java
- src/main/java/com/starrocks/connector/flink/row/sink/StarRocksTableRowTransformer.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunction.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksVersionedSerializer.java
- src/main/java/com/starrocks/connector/flink/tools/JsonWrapper.java
- src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java
- src/test/java/com/starrocks/connector/flink/row/sink/StarRocksJsonSerializerTest.java
Fixes #
If a job fails many times, flink can warn there is a classloader leak when fastjson serializes/deserializes data
`Caused by: java.lang.IllegalStateException: Trying to access closed classloader. Please check if you store classloaders directly or indirectly in static fields. If the stacktrace suggests that the leak occurs in a third party library and cannot be fixed immediately, you can disable this check with the configuration 'classloader.check-leaked-classloader'.`
Fastjson uses two global/static configs by default to serialize and deserialize data (SerializeConfig#globalInstance and ParserConfig#global). Flink's classloader mechanism will treat them as classloader leak if a JVM instance run a job in multiple times, such as failover or in session mode. See flink …
> [Bugfix] Fix fastjson classloader leaked

- starrocks-stream-load-sdk/pom.xml
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadTableProperties.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/FlushAndCommitStrategy.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/FlushReason.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/TransactionTableRegion.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/FlushAndCommitStrategyTest.java
Fixes #
This PR adds a new flush strategy that trigger flush if the number of buffered rows in a table reaches the limitation. It's helpful for some users to verify the result in the loading process according to count(*) which should be the multiple times of the number of rows limitation.
> [Feature] Support to trigger flush according to the number of rows

- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java
Fixes #
```
java.lang.NullPointerException: null;
at java.util.LinkedList$ListItr.next(LinkedList.java:893);
at com.starrocks.connector.flink.manager.StarRocksSinkManagerV2.lambda$init$0(StarRocksSinkManagerV2.java:158);
```
`StreamLoadManagerV2#flushQ` could be read and write concurrently, but it's a `LinkedList` which is not a concurrent data structure. We can replace it with `ConcurrentLinkedQueue`. At the same time, fix the potential concurrent problem for `regions`.
> [Bugfix] Fix NPE caused by concurrent access

- src/main/java/com/starrocks/connector/flink/table/sink/ExactlyOnceLabelGenerator.java
- src/main/java/com/starrocks/connector/flink/table/sink/ExactlyOnceLabelGeneratorFactory.java
- src/main/java/com/starrocks/connector/flink/table/sink/ExactlyOnceLabelGeneratorSnapshot.java
- src/main/java/com/starrocks/connector/flink/table/sink/LingeringTransactionAborter.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicSinkFunctionV2.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicTableSinkFactory.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarrocksSnapshotState.java
- src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java
- src/test/java/com/starrocks/connector/flink/table/sink/ExactlyOnceLabelTest.java
- src/test/java/com/starrocks/connector/flink/table/sink/LingeringTransactionAborterTest.java
- src/test/java/com/starrocks/connector/flink/table/sink/StarrocksSnapshotStateTest.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/BatchTableRegion.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoadManager.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/LabelGenerator.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/LabelGeneratorFactory.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoadConstants.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamTableRegion.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TableRegion.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStatus.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/TransactionTableRegion.java
Fixes #
When using exactly-once,  the connector will not abort the `PREPARED` transactions when the flink job failovers or exits because it's 2PC mechanism. Some of those PREPARED transactions may be in a successful checkpoint, and will be committed when the job restores from the checkpoint, but some of them are just useless, and should be aborted, otherwise they will be lingering in StarRocks until timeout which maybe make StarRocks unstable. We should try to abort those lingering transactions when restoring
When flink job restores, the connector will try to find those lingering transactions, and abort them. The key is how to find those transactions because the labels of them are not stored in the checkpoint. Here we design a label generator (ExactlyOnceLabelGenerator) to solve it
1. the …
> [Enhancement] Try to cleanup lingering transactions when restoring in exactly-once mode

- src/main/java/com/starrocks/connector/flink/manager/StarRocksSinkManager.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/TransactionTableRegion.java
> [Enhancement] Return the first exception after retry

- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoadManager.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadProperties.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadTableProperties.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java
Fixes #
For the Stream Load SDK, if the table to be written to is a non-default table, the DefaultStreamLoader.send method still requests SR to write data to the default table, causing the stream load job to fail. This PR fixes this issue.
> [BugFix] Fix SDK write failure for non-default tables

- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
> [Enhancement] Increase default sink.connect.timeout-ms to to tolerate jitter

- src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadVisitor.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicTableSinkFactory.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/TransactionStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadProperties.java
Fixes #
Add a configuration `sink.socket.timeout-ms`. It's the timeout in milliseconds that the http client waits for data or, put differently, a maximum period inactivity between two consecutive data packets. The default value -1 is same as that of apache http client which is interpreted as undefined (system default if applicable). A timeout value of zero is interpreted as an infinite timeout. You can use this option to fail the stream load from the connector side if the http client does not receive response from StarRocks before timeout. The other option `sink.properties.timeout` take effects on the StarRocks side, but the response to the client may delay in some unexpected cases. If you want to have a strict timeout from the connector side, you can set this option to an acceptable …
> [Enhancement] Support to configure socket timeout

- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/DefaultStreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoader.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/TransactionTableRegion.java
Fixes #
For transaction stream load at at-least-once mode, only load phase is executed asynchronously in a thread pool whose size is controlled by `sink.io.thread-count` , but the prepare/commit phase is executed in the single thread used for schedule, and it can block the schedule thread if prepare/commit takes much time. For multiple tables case,  this can prevent to schedule other tables to load/prepare/commit, and lead to performance issue. So we make the prepare/commit also  asynchronous.
> [Enhancement] Prepare/commit transaction stream load asynchronously

- src/main/java/com/starrocks/connector/flink/row/source/StarRocksSourceFlinkRows.java
- src/main/java/com/starrocks/connector/flink/table/source/struct/Column.java
- src/main/java/com/starrocks/connector/flink/table/source/struct/StarRocksSchema.java
- src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java
StarRocks supports conversion from JSON type to Arrow String type in https://github.com/StarRocks/starrocks/pull/25044 , so connector can support read StarRocks json column to Spark string now
> [Enhancement] Support to read json column

- docs/content/Realtime synchronization from MySQL.md
- src/main/java/com/starrocks/connector/flink/cdc/DatabaseSync.java
- src/main/java/com/starrocks/connector/flink/cdc/StarRocksOptions.java
- src/main/java/com/starrocks/connector/flink/cdc/json/DebeziumJsonSerializer.java
- src/test/java/com/starrocks/connector/flink/cdc/StarRocksCdcToolsTest.java
> [Enhancement]  Synchronize ddl schema change to Starrocks by parsing json

- docs/content/connector-sink.md
> [Doc] Fix wrong flink cdc link

- src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicLookupFunction.java
- src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicSourceFunction.java
- src/main/java/com/starrocks/connector/flink/table/source/StarRocksDynamicTableSource.java
- src/main/java/com/starrocks/connector/flink/table/source/struct/PushDownHolder.java
- src/test/java/com/starrocks/connector/flink/it/source/StarRocksSourceBaseTest.java
- src/test/java/com/starrocks/connector/flink/it/source/StarRocksSourceITTest.java
- src/test/java/com/starrocks/connector/flink/manager/source/StarRocksQueryPlanVisitorTest.java
- src/test/java/com/starrocks/connector/flink/table/source/StarRocksDynamicTableSourceTest.java
Fixes #
Currently columns between Flink schema and StarRocks schema must be same. It's not easy to use if the StarRocks table has thousands of columns, but the user only wants to read some columns of it. This PR supports to define the Flink source table only with some columns of StarRocks table that need to read. For example,
StarRocks schema
```
CREATE TABLE t (
c0 INT,
c1 FLOAT,
c3 STRING
);
```
If you just want to read c0 and c3, you can define flink source table as follows. Before this PR, must include all columns
```
CREATE TABLE t (
c0 INT,
c3 STRING
) WITH (
......
)
```
> [Enhancement] Support to map a subset of StarRocks columns to Flink source table

- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
- src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java
- starrocks-stream-load-sdk/pom.xml
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/StreamLoadDataFormat.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/annotation/Evolving.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/compress/CompressionCodec.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/compress/CompressionHttpEntity.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/compress/CompressionOptions.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/compress/CountingOutputStream.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/compress/LZ4FrameCompressionCodec.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/properties/StreamLoadTableProperties.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/ChunkHttpEntity.java
- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/TransactionTableRegion.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/ChunkHttpEntityTest.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/ChunkInputStreamTest.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/compress/CompressionCodecTestBase.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/compress/CompressionHttpEntityTest.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/compress/CountingOutputStreamTest.java
- starrocks-stream-load-sdk/src/test/java/com/starrocks/data/load/stream/compress/LZ4FrameCompressionCodecTest.java
After StarRocks supports lz4 compression for stream load json format in https://github.com/StarRocks/starrocks/pull/43732, the connector can compress the json data before sending to StarRocks which will reduce the network traffic significantly.  In the test to load clickbench data to starrocks, the compression ratio can be ~8, and the load performance has a 3.64% degradation which is acceptable.
You can enable it with the following configuration
```
'sink.properties.format' = 'json'
'sink.properties.compression' = 'lz4_frame'
```
> [Feature] Sink supports LZ4 compression with json format

- src/main/java/com/starrocks/connector/flink/row/sink/StarRocksTableRowTransformer.java
- src/test/java/com/starrocks/connector/flink/it/sink/StarRocksSinkITTest.java
When loading empty json string to json column, there will be the following exception. 
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
at java.lang.String.charAt(String.java:658)
at com.starrocks.connector.flink.row.sink.StarRocksTableRowTransformer.typeConvertion(StarRocksTableRowTransformer.java:135)
at com.starrocks.connector.flink.row.sink.StarRocksTableRowTransformer.transform(StarRocksTableRowTransformer.java:96)
at com.starrocks.connector.flink.row.sink.StarRocksTableRowTransformer.transform(StarRocksTableRowTransformer.java:50)
at com.starrocks.connector.flink.table.sink.StarRocksDynamicSinkFunctionV2.invoke(StarRocksDynamicSinkFunctionV2.java:164)
at org.apache.flink.table.runtime.operators.sink.SinkOperator.processElement(SinkOperator.java:65)
at …
```
> [BugFix] Fix exception when loading empty json string to json column

- src/main/java/com/starrocks/connector/flink/manager/StarRocksStreamLoadVisitor.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksDynamicTableSinkFactory.java
- src/main/java/com/starrocks/connector/flink/table/sink/StarRocksSinkOptions.java
When inserting data like the below:
```java
String[] records = new String[]{
"[{\"id\":400, \"name\":\"400\"}]",
"[{\"id\":500, \"name\":\"500\"}]"
};
DataStream<String> source = env.fromElements(records);
```
It fails since connector wrapped the json array into json array's array.
Fixes #
> [Enhancement] Add an option to disable wrapping json to json array.

- starrocks-stream-load-sdk/src/main/java/com/starrocks/data/load/stream/v2/StreamLoadManagerV2.java
Fixes [#448](https://github.com/StarRocks/starrocks-connector-for-apache-flink/issues/448)
Add exception check in `isSavepointFinished` to prevent `flush` from skipping commit-related exceptions.
- Introduced validation in `isSavepointFinished` to check for exceptions in the `StreamLoadManager` instance's `e` property.
- Ensures that commit failures (e.g., exceptions in `doCommit`) are properly detected and handled.
- Prevents the `flush` function from incorrectly marking operations as successful when commit exceptions occur.
- Improves data integrity by avoiding false-positive flush completions that could lead to upstream and downstream data inconsistencies.
- Stabilizes Flink checkpoints by ensuring they are not marked successful during underlying commit failures.
> [BugFix] Add exception check in isSavepointFinished to prevent flush from skipping commit-related exceptions.
